# Use Node.js base image
FROM node:22

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy project files
COPY . .

# Expose port
EXPOSE 4200

# Start Angular in development mode with live reload
CMD ["npm", "run", "start"]
